# Generated by Django 5.1.2 on 2026-06-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_candidateprofile_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'verbose_name_plural': 'Candidate Profiles'},
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='can_work_weekends_holidays',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='expected_salary',
            field=models.CharField(blank=True, help_text='Rango salarial pretendido', max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='gastro_courses',
            field=models.TextField(blank=True, help_text='Cursos gastronómicos realizados'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='has_food_handling_cert',
            field=models.BooleanField(default=False, help_text='¿Carnet de manipulación de alimentos?'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='has_own_transport',
            field=models.BooleanField(default=False, help_text='¿Movilidad propia?'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='has_sanitary_license',
            field=models.BooleanField(default=False, help_text='¿Libreta Sanitaria vigente?'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='observations',
            field=models.TextField(blank=True, help_text='Observaciones adicionales'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='primary_education',
            field=models.CharField(blank=True, choices=[('completo', 'Completo'), ('incompleto', 'Incompleto')], max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='schedule',
            field=models.CharField(blank=True, choices=[('manana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche'), ('full_time', 'Full Time')], max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='secondary_education',
            field=models.CharField(blank=True, choices=[('completo', 'Completo'), ('incompleto', 'Incompleto')], max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.CharField(blank=True, help_text='Habilidades (separadas por comas o JSON)', max_length=500),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='social_networks',
            field=models.CharField(blank=True, help_text='LinkedIn, Instagram, Facebook, etc. (opcional)', max_length=500),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='tertiary_details',
            field=models.TextField(blank=True, help_text='Detalle de estudios terciarios/universitarios'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='tertiary_education',
            field=models.BooleanField(default=False, help_text='¿Tiene educación terciaria/universitaria?'),
        ),
    ]
