# Generated by Django 5.1.2 on 2026-06-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_categoryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('hombre', 'Hombre'), ('mujer', 'Mujer')], max_length=10),
        ),
    ]
